name: evictmem-ctm
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - pip
  - pip:
      - --index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0+cu128
